development:
  rack_cors_origins:    <%= ENV["RACK_CORS_ORIGINS"] %>
  localhost:            <%= ENV["LOCALHOST"] %>
  access_token:         <%= ENV["ACCESS_TOKEN"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_access_token:  <%= ENV["SECRET_ACCESS_TOKEN"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_access_token:  <%= ENV["SECRET_ACCESS_TOKEN"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>
