import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return [
      {id: 1, color:'ivory',            hex:'fffff0'},
      {id: 2, color:'dark khaki',       hex:'bdb76b'},
      {id: 3, color:'honeydew',         hex:'f0fff0'},
      {id: 4, color:'lavender blush',   hex:'fff0f5'},
      {id: 5, color:'blue violet',      hex:'8a2be2'},
      {id: 6, color:'light cyan',       hex:'e0ffff'},
      {id: 7, color:'dark green',       hex:'006400'},
      {id: 8, color:'chocolate',        hex:'d2691e'},
      {id: 9, color:'light coral',      hex:'f08080'},
      {id:10, color:'burlywood',        hex:'deb887'},
      {id:11, color:'hot pink',         hex:'ff69b4'},
      {id:12, color:'dark sea green',   hex:'8fbc8f'},
      {id:13, color:'bisque',           hex:'ffe4c4'},
      {id:14, color:'light blue',       hex:'add8e6'},
      {id:15, color:'dark olive green', hex:'556b2f'},
      {id:16, color:'lavender',         hex:'e6e6fa'},
      {id:17, color:'dark turquoise',   hex:'00ced1'},
      {id:18, color:'light',            hex:'eedd82'},
      {id:19, color:'forest green',     hex:'228b22'},
      {id:20, color:'alice blue',       hex:'f0f8ff'},
      {id:21, color:'green yellow',     hex:'adff2f'},
      {id:22, color:'dim gray',         hex:'696969'},
      {id:23, color:'cadet blue',       hex:'5f9ea0'},
      {id:24, color:'cornflower blue',  hex:'6495ed'},
      {id:25, color:'cyan',             hex:'00ffff'},
      {id:26, color:'lawn green',       hex:'7cfc00'},
      {id:27, color:'floral white',     hex:'fffaf0'},
      {id:28, color:'khaki',            hex:'f0e68c'},
      {id:29, color:'dark golden rod',  hex:'b8860b'},
      {id:30, color:'aquamarine',       hex:'7fffd4'},
      {id:31, color:'blanched almond',  hex:'ffebcd'},
      {id:32, color:'cornsilk',         hex:'fff8dc'},
      {id:33, color:'gainsboro',        hex:'dcdcdc'},
      {id:34, color:'gray',             hex:'bebebe'},
      {id:35, color:'lemon chiffon',    hex:'fffacd'},
      {id:36, color:'dark salmon',      hex:'e9967a'},
      {id:37, color:'chartreuse',       hex:'7fff00'},
      {id:38, color:'ghost white',      hex:'f8f8ff'},
      {id:39, color:'antique white',    hex:'faebd7'},
      {id:40, color:'indian red',       hex:'cd5c5c'},
      {id:41, color:'dark orchid',      hex:'9932cc'},
      {id:42, color:'azure',            hex:'f0ffff'},
      {id:43, color:'goldenrod',        hex:'daa520'},
      {id:44, color:'brown',            hex:'a52a2a'},
      {id:45, color:'firebrick',        hex:'b22222'},
      {id:46, color:'dark violet',      hex:'9400d3'},
      {id:47, color:'beige',            hex:'f5f5dc'},
      {id:48, color:'dark orange',      hex:'ff8c00'},
      {id:49, color:'coral',            hex:'ff7f50'},
      {id:50, color:'dark slate gray',  hex:'2f4f4f'}
    ];
  }
});
